# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision :shell do |shell|
    shell.inline = 'su vagrant -c /vagrant/start'
    shell.inline = 'echo So begins a new age of knowledge'
  end

  config.vm.define "wheezy" do |wheezy|
    wheezy.vm.hostname = "wheezy"
    wheezy.vm.box = "wheezy"
    wheezy.vm.box_url = ["https://github.com/jose-lpa/packer-debian_7.6.0/releases/download/1.0/packer_virtualbox-iso_virtualbox.box"]
    wheezy.vm.network :forwarded_port, host: 3000, guest: 3000
    wheezy.vm.synced_folder '.', '/vagrant', disabled: true
  end

  config.vm.define "jessie" do |jessie|
    jessie.vm.hostname = "jessie"
    jessie.vm.box = ENV.fetch('VAGRANT_BOX', "debian/jessie64")
    jessie.vm.network :forwarded_port, host: 4000, guest: 4000
    jessie.vm.synced_folder '.', '/vagrant', disabled: true
  end

end
